# Generated by Django 5.2.1 on 2025-05-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookingsite_raw_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsite',
            name='raw_shift',
        ),
        migrations.AddField(
            model_name='slot',
            name='raw_shift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
