# Generated by Django 5.2.1 on 2025-05-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_bookingsite_raw_shift_slot_raw_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
